### ISSUE TITLE
How can I use GPU in test_frcnn.py?

### ISSUE THREAD

**Issue by chamecall** [kentaroy47/frcnn-from-scratch-with-keras#14]
Cause it uses cpu

**Comment by chamecall** [comment]
Can you comment that?

**Comment by kentaroy47** [comment]
that's weird because keras should grab the GPU when the  device is available.
can you post the logs?

**Comment by chamecall** [comment]
Thanks. That was related with PyCharm. It didn't find the needed libraries. Under the terminal it launches ok.
