### ISSUE TITLE
Failed train_rpn.py

### ISSUE THREAD

**Issue by syifalaili26** [kentaroy47/frcnn-from-scratch-with-keras#2]
Hello, I've tried to run train_rpn.py , but I got some error like this. Maybe you can explain it to me
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "train_rpn.py", line 18, in <module>
    from keras_frcnn import config_anc9 as config
ImportError: cannot import name 'config_anc9'
```

**Comment by kentaroy47** [comment]
sorry, that was my test configuration.
by fixing line 18 to 
```
from keras_frcnn import config
```
it should run properly. let me fix this.

**Comment by syifalaili26** [comment]
I can run it now, but it's always running so long at epoch 1. Am I wrong at some steps?
 `{'retak_aligator': 179, 'retak_garis': 178, 'lubang': 174}
Training images per class:
{'bg': 0, 'lubang': 174, 'retak_aligator': 179, 'retak_garis': 178}
Num classes (including bg) = 4
Config has been written to config.pickle, and can be loaded when testing to ensure correct results
Num train samples 360
Num val samples 0
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
loading weights from ./resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5
loaded weights!
Starting training
Epoch 1/250
399/400 [============================>.] - ETA: 0s - loss: 3.9409 - rpn_out_class_loss: 3.4894 - rpn_out_regress_loss: 0.4515`

**Comment by kentaroy47** [comment]
hi @syifalaili26 
it will depend on how large your dataset is.
You might want to test with a smaller dataset? and 250 epoch might be too long.. 20~50 should be enough.

it will be slow if you don't have GPU acceleration too.

**Comment by syifalaili26** [comment]
I use 360 datasets, how many epoch normally should I use?

**Comment by kentaroy47** [comment]
20 epochs should be enough.
you should toggle few learning rates and find out which one works the best

**Comment by syifalaili26** [comment]
Thank you, I'll try it again

**Comment by syifalaili26** [comment]
I still can't train RPN, always loading at epoch 1, I've used 20 epoch as you suggest but still not working. Can you help me?

**Comment by kentaroy47** [comment]
@syifalaili26 
What is the problem you are getting? if it's a error, it would help if you post the message.
Or do you get stuck at the end of epoch 1?

```
Starting training Epoch 1/250 399/400 [============================>.] - ETA: 0s - loss: 3.9409 - rpn_out_class_loss: 3.4894 - rpn_out_regress_loss: 0.4515
```

instead of your custom datasets, can you try running with known datasets like VOC2007 or KITTI?
