### ISSUE TITLE
inferring with mobilenetv2 causes improper tensor shape error

### ISSUE THREAD

**Issue by asfix** [kentaroy47/frcnn-from-scratch-with-keras#23]
After I successfully trained RPN and whole network with mobilenetv2, I wanted to get results through test_frcnn.py

However, though my parameters were carefully typed and set, I got this error at very beginning.

Loading weights from ./models/mobilenetv2/voc.hdf5
Traceback (most recent call last):
  File "test_frcnn.py", line 194, in <module>
    model_classifier.load_weights(options.load, by_name=True)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1163, in load_weights
    reshape=reshape)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 1149, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #153 (named "conv1_td"), weight <tf.Variable 'conv1_td/kernel:0' shape=(3, 3, 512, 512) dtype=float32_ref> has shape (3, 3, 512, 512), but the saved weight has shape (512, 320, 3, 3).

As you see, my trained model has been saved in "/models/mobilenetv2/voc.hdf5". Did not you try this scheme before publishing it? Could you please help me? What is wrong? By the way, my 2 phase training was ok and I have seen the decrease in loss. My dataset is custom and contains 16 classes including 'bg' and I have simulated the dataset structure of vockit.
Here is my test argument line:

python3 test_frcnn.py --network mobilenetv2 -p ./VOCdevkit2007/VOC2007/TestImages/ --load ./models/mobilenetv2/voc.hdf5 --write

**Comment by kentaroy47** [comment]
@asfix 
sorry for this bug, there was a name overlap in the model.
it has been fixed in the commit.

```
python test_frcnn.py --network mobilenetv2 -p ../VOCdevkit/VOC2007/JPEGImages/ --write --load models/mobilenetv2/voc.hdf5 
Using TensorFlow backend.
{0: 'dog', 1: 'cat', 2: 'car', 3: 'person', 4: 'chair', 5: 'bottle', 6: 'diningtable', 7: 'pottedplant', 8: 'bird', 9: 'horse', 10: 'motorbike', 11: 'bus', 12: 'tvmonitor', 13: 'sofa', 14: 'boat', 15: 'cow', 16: 'aeroplane', 17: 'train', 18: 'sheep', 19: 'bicycle', 20: 'bg'}
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Loading weights from models/mobilenetv2/voc.hdf5
000005.jpg
```
