### ISSUE TITLE
GPU out of memory error

### ISSUE THREAD

**Issue by humayunr7** [kentaroy47/frcnn-from-scratch-with-keras#24]
I am getting out of memory error. How much GPU mem is required to train with batch size 32?

**Comment by kentaroy47** [comment]
depends on your data, but bs=32 may take up about 16GB of memory.
try halving the batch size?

**Comment by ALIENK9** [comment]
I have a similar problem, but how can I change the batch size?
Thanks.

**Comment by kentaroy47** [comment]
>If you run out of memory, try reducing the number of ROIs that are processed simultaneously. Try passing a lower -n to train_frcnn.py. Alternatively, try reducing the image size from the default value of 600 (this setting is found in config.py.
