### ISSUE TITLE
I want to add Precision and Recall metrics to this repo, have you started working on it ?

### ISSUE THREAD

**Issue by AlphonsGwatimba** [kentaroy47/frcnn-from-scratch-with-keras#29]
#6 
Above you said this my friend:
> I guess you want to see the calculated mAP? I will work with that feature so plz wait.

I can do it, but I dont think it will be coco format. Just reporting Precision and Recall. Will you merge?

**Comment by kentaroy47** [comment]
Thanks,  can you raise a PR?
That will help :)

**Comment by AlphonsGwatimba** [comment]
> Thanks, can you raise a PR?
> That will help :)

Oh I mean I will start working on it, because I dont wanna start if u are nearly finished or something. It sounds like u want the help so I will start. Thank you for this project btw and maintaining

**Comment by kentaroy47** [comment]
That will help because I haven’t started working on it.
Thanks for your great help! ☺
