### ISSUE TITLE
TypeError: get_data() takes 1 positional argument but 2 were given`

### ISSUE THREAD

**Issue by ianstath** [kentaroy47/frcnn-from-scratch-with-keras#30]
`  File "train_frcnn.py", line 107, in <module>
    all_imgs, classes_count, class_mapping = get_data(options.train_path, options.cat)
TypeError: get_data() takes 1 positional argument but 2 were given`

Hey @kentaroy47 ,
Thank you very much for the project.
I am getting the above error (I am really new in this). Could you please help? My training set is having 2 categories (2 classes is the same?). I successfully train the rpn model, but when i proceed to train the whole frcnn this happened.

**Comment by ianstath** [comment]
Update:
I just removed the `options.cat` from `get_data` and the training started. Will it affect the results? Should i stop the training (2 hrs per epoch for 50 epochs in my CPU)

**Comment by kentaroy47** [comment]
No, it should work fine without it.
Sorry I will fix this bug later.

2019年9月22日(日) 22:11 ianstath <notifications@github.com>:

**Comment by jainakhil88** [comment]
> I just removed the `options.cat` from `get_data` and the training started. Will it affect the results? Should i stop the training (2 hrs per epoch for 50 epochs in my CPU)

How and where to remove this?
