### ISSUE TITLE
verstion of keras  & assertion error

### ISSUE THREAD

**Issue by Enoch07** [kentaroy47/frcnn-from-scratch-with-keras#33]
when I tried to run the model I got the below error. also, I recogn version of Keras are deprecated how this can be fixed 

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4267: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4409: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

Traceback (most recent call last):
  File "train_frcnn.py", line 156, in <module>
    classifier = nn.classifier(shared_layers, roi_input, C.num_rois, nb_classes=len(classes_count), trainable=True)
  File "/content/drive/My Drive/object detector/frcnn-from-scratch-with-keras-master/keras_frcnn/vgg.py", line 109, in classifier
    out_roi_pool = RoiPoolingConv(pooling_regions, num_rois)([base_layers, input_rois])
  File "/content/drive/My Drive/object detector/frcnn-from-scratch-with-keras-master/keras_frcnn/RoiPoolingConv.py", line 30, in __init__
    assert self.dim_ordering in {'tf', 'th'}, 'dim_ordering must be in {tf, th}'
AssertionError: dim_ordering must be in {tf, th}

**Comment by kentaroy47** [comment]
what's your keras ver?

**Comment by Enoch07** [comment]
version of keras2.2.5

**Comment by kentaroy47** [comment]
Downgrading to 2.2.4 may fix your problem.
