### ISSUE TITLE
in the requirement keras is mentioned but did not mention which version of keras to install. because in the latest version most of the methods used here is depreciated can some one suggest version for both keras and tensorflow also  will be better if all version of all the dependencies mentioned in the requirement.txt  are knowm

### ISSUE THREAD

**Issue by Enoch07** [kentaroy47/frcnn-from-scratch-with-keras#34]
in the requirement, keras is mentioned but did not mention which version of keras to install. because in the latest version most of the methods used here is depreciated can someone suggest version for both keras and tensorflow

**Comment by kentaroy47** [comment]
I don't have plans to support the newest keras immediately (TF2.0 has lots of breaking changes and have to keep up on that too..)
will work on when things chill out a bit.
