### ISSUE TITLE
DenseNet support

### ISSUE THREAD

**Issue by Yousuf-CS** [kentaroy47/frcnn-from-scratch-with-keras#35]
What changes i need to make in order to add dense net support ? I get the idea behinf nn_base method returning the feature maps. But why the classification layers are different for different base networks ?

**Comment by kentaroy47** [comment]
For resnet50, the output channel is 512 so I used a different
classification layers. You should change the classification layer according
to the output Chanel's of your Densenet.
Good luck!

2019年10月4日(金) 2:29 M.Yousuf <notifications@github.com>:
