### ISSUE TITLE
Anchor box more bigger than the image

### ISSUE THREAD

**Issue by syifalaili26** [kentaroy47/frcnn-from-scratch-with-keras#4]
Hello I want to ask, I tried to use this model to implement on my own dataset, but the anchor always bigger than the image. How to solve it?

**Comment by kentaroy47** [comment]
can you post how it shows on your image?
do you mean the final output?
thanks.

**Comment by syifalaili26** [comment]
Yes, I mean the output images. Here how it show on my images, also some
output images show more than 1 bounding box for the same object. I hope you
can help me with this. Thank you for your time and consideration, I wait
for your reply.

**Comment by kentaroy47** [comment]
@syifalaili26  
do you think you can post the direct image, so we can understand what your problem is?
that will greatly help! thanks

**Comment by syifalaili26** [comment]
If you don't mind, you can see the result [https://drive.google.com/folderview?id=1_0w7a-wnY2mu0P0UBkXEAtOm5w-61nIe](url)
Thank you

**Comment by kentaroy47** [comment]
Hmm.. I cannot access the url..

2019年6月29日(土) 21:12 Syifa Laili Hapsari Oktavian <notifications@github.com>:

**Comment by syifalaili26** [comment]
[https://drive.google.com/file/d/11zTZI91-4n-04Q2VhxxILXHTN7STRmpp/view?usp=sharing](url), sorry I've forgotten to open share link

**Comment by kentaroy47** [comment]
Can you directly post the image to here as in #1?
I still can't access..

**Comment by syifalaili26** [comment]
![2](https://user-images.githubusercontent.com/40890898/60395956-56191f80-9b65-11e9-871b-e29ccaec53a7.png)
![84](https://user-images.githubusercontent.com/40890898/60395957-56b1b600-9b65-11e9-9833-8954aec92afa.png)
Sorry, just open it

**Comment by kentaroy47** [comment]
ok, thanks for the images.  btw, are these training images?
 
anyway,

1) the anchor scale is defined here.
https://github.com/kentaroy47/frcnn-from-scratch-with-keras/blob/master/keras_frcnn/config.py

line 18
`self.anchor_box_scales = [128, 256, 512]`

you may want to use smaller scales.

2) if that does not solve the problem, you may want to add more data to your dataset since the model might be struggling to learn.

**Comment by syifalaili26** [comment]
Thank you for your help
