### ISSUE TITLE
config.pickle file to be used for downloaded pre-trained weight form vgg16 https://drive.google.com/file/d/1IgxPP0aI5pxyPHVSM2ZJjN1p9dtE4_64/view?usp=sharing

### ISSUE THREAD

**Issue by Enoch07** [kentaroy47/frcnn-from-scratch-with-keras#44]
config.pickle file to be used for downloaded pre-trained weight form vgg16 https://drive.google.com/file/d/1IgxPP0aI5pxyPHVSM2ZJjN1p9dtE4_64/view?usp=sharing

**Comment by kentaroy47** [comment]
Can you be specific about the issue? Thanks!

**Comment by Enoch07** [comment]
when we download  pre-trained weight from the url  https://drive.google.com/file/d/1IgxPP0aI5pxyPHVSM2ZJjN1p9dtE4_64/view?usp=sharing, "config.picle" file  does not download along with the voc.hdf5 file, for testing this file is required how we can resolve this problem

**Comment by kentaroy47** [comment]
Thanks for further comments!
I will upload the `config.pickle` as well when I get back.

**Comment by Enoch07** [comment]
Thank you

**Comment by kentaroy47** [comment]
can you try this link?
https://drive.google.com/open?id=1BL_2ZgTf55vH2q1jvVz0hkhlWYgj-coa

**Comment by Enoch07** [comment]
Thank you

**Comment by Enoch07** [comment]
can you please let us know on what data set it has been trained.

**Comment by kentaroy47** [comment]
It's on VOC2007

2019年10月22日(火) 13:55 Enoch07 <notifications@github.com>:

**Comment by Enoch07** [comment]
Hello,

for the training what is the data set has been used (for instance ms coco,
pascal VOC 2007,  kitty .., )
