### ISSUE TITLE
Raise Value Error - Not a valid model

### ISSUE THREAD

**Issue by May-Tere** [kentaroy47/frcnn-from-scratch-with-keras#48]
Hi guys,

I downloaded vgg or other pretrained model(s) from the related link(s) and placed it in the root directory. However, when i used the command below:

**python train_rpn.py --network vgg -o simple -p /mypathforannotations**

I am given the error:

**Not a valid model**
Traceback (most recent call last):
  File "train_rpn.py", line 113, in <module>
    raise ValueError
**ValueError**

Why cannot the code "train_rpn.py" find the model? May be you can describe step by step after downloading the weights, where can we placed them and how can we name these files?

Would you kindly help me, I will be pleased.

**Comment by kentaroy47** [comment]
can you try placing the weights in the `root/pretrain` directory?

thanks!

**Comment by basturk** [comment]
Instead of `root/pretrain` directory, `root` directory solved my issue. The problem was solved after an afresh installation. Thank you...

**Comment by May-Tere** [comment]
Thank you. Regards.
