### ISSUE TITLE
How to train the Model with GPU

### ISSUE THREAD

**Issue by ani16** [kentaroy47/frcnn-from-scratch-with-keras#53]
Hi

The model is successfully running on cpu , but how to run the same model on GPU .I have Nvidia K40.

Secondly, input weight file can be used to place pretrained model? For testing the model for voc , I just need to load the trained model weight ?

**Comment by kentaroy47** [comment]
keras should run GPU when it is available. does it grab GPU when training for tutorials like MNIST?

>I just need to load the trained model weight ?
you should just load the trained weight.
