### ISSUE TITLE
Added eval for VOC

### ISSUE THREAD

**Issue by GMahdi** [kentaroy47/frcnn-from-scratch-with-keras#58]
I want to evaluate the model for VOC, as it is described that the model can be evaluated for VOC, pcan someone please describe how to do it? Thanks

**Comment by kentaroy47** [comment]
Can you take a look at `eval.ipynb`, thanks!

**Comment by GMahdi** [comment]
Thanks a lot for the prompt reply. One more thing, I can' find voc_best.hdf5; the model need to be trained and then the best weights would be used for evaluation or I can use available voc.h5? Thanks again
