### ISSUE TITLE
Hot to convert hdf5 to pb?

### ISSUE THREAD

**Issue by TomasTrnkaPLC** [kentaroy47/frcnn-from-scratch-with-keras#60]
I have another question. Can you please provide a running example of how to convert the output to another format like pb? I try a few conversion scripts but, without success.

**Comment by kentaroy47** [comment]
I'm not sure if this is a frcnn issue but did you try what the blog post says?

I understand it may be difficult since object detection models are complex..

https://www.dlology.com/blog/how-to-run-keras-model-inference-x3-times-faster-with-cpu-and-intel-openvino-1/

**Comment by TomasTrnkaPLC** [comment]
I not sure if you answering my question or question of someone else. 
However can you please provide a clear solution how to transfer hdf5 output from YOUR project to pb file? I know on the internet is 100+1 theoretically solutions how to do it but, I cannot find one who can run. Everyone have a some example like a copy / paste one million time but, when I ask how to move hdf5 to pb no one can answer with the normal answer but only send a link on code what he never tries.

**Comment by kentaroy47** [comment]
closing since this is not related to frcnn but a keras question.
