### ISSUE TITLE
can you provide pre-trained model?

### ISSUE THREAD

**Issue by TaeheeJeong** [kentaroy47/frcnn-from-scratch-with-keras#62]
Can you provide pre-trained model?
whether basemodel: vgg16 or resnet50

Thanks

**Comment by kentaroy47** [comment]
hi, it's in the readme.

VGG16:
https://drive.google.com/file/d/1IgxPP0aI5pxyPHVSM2ZJjN1p9dtE4_64/view?usp=sharing

**Comment by TaeheeJeong** [comment]
Hello Kentaro

Even though I used the file, the detection is empty.

Can you check it and provide updated one?

Thanks

Taehee
