### ISSUE TITLE
No detection in test_frcnn.py

### ISSUE THREAD

**Issue by TaeheeJeong** [kentaroy47/frcnn-from-scratch-with-keras#66]
Hello

I tried to test+frcnn model using the pretrained weights as below.

The pretrained RPN for VGG is uploaded to:
https://drive.google.com/file/d/1teuXIRN4mvmbnIfWlxAAM69hJEceTpUm/view?usp=sharing
The trained vgg frcnn model is uploaded (is underfitting..):
https://drive.google.com/file/d/1IgxPP0aI5pxyPHVSM2ZJjN1p9dtE4_64/view?usp=sharing

When I tried to test frcnn model using any image from VOC2007, the output of probs and bboxes are empty.

Please provide any working weights.
Thanks

**Comment by kentaroy47** [comment]
The pretrained model should get predictions since accuracies were evaluated out of them.
#6 may help you solve if you're training your own model.
