### ISSUE TITLE
Getting confidence score/distributions for all objects

### ISSUE THREAD

**Issue by GMahdi** [kentaroy47/frcnn-from-scratch-with-keras#67]
Thanks for the great work; I am trying to get distributions for all objects of test dataset of Pascal 07. It means instead of giving maximum score for a bounding box, I want to print score for scores for all 20 objects. Is there a way to get it? thanks

**Comment by GMahdi** [comment]
The idea is get score for all 20 objects not the only one which have the highest score; my understanding at some place it is being done argmax to get the label but how to get all the list.

**Comment by kentaroy47** [comment]
The predictions are not filtered by argmax but filtered out by threshold as: `confidence < bbox_threshold`.
You can set bbox_threshold to a low value (e.g. 0.05) to get all of the objects.

https://github.com/kentaroy47/frcnn-from-scratch-with-keras/blob/master/test_voc.py#L177
