### ISSUE TITLE
RPN, Faster R-CNN training way & ResNet-50 Arch

### ISSUE THREAD

**Issue by TiasM** [kentaroy47/frcnn-from-scratch-with-keras#72]
Hi, i'd like to ask, In the original Faster R-CNN paper, there are 3 ways to train Faster R-CNN. Namely Alternating training, Approximate Joint Training and Non-approximate joint training. Can you please explain which one is used in this repo ? Also, i'm quite difficult to understand the training flow both RPN and Faster-RCNN on this repo. Can anyone help me out please ? I'm relatively new to this filed. Your answers will be helpful for me. Thanks

**Comment by TiasM** [comment]
I also want to ask a couple of things regarding the architecture setting for Faster R-CNN using ResNet-50:
1. In the resnet.py file, line 221, why the Conv2D layer of RPN use 512 depth filter ? shouldn't it be 2048 (the same as the output depth of last resnet-50 layer before the avg pooling layer) ? Or reducing the dimension here doesn't matter at all since we will only use the anchor later on (+ RoI pooling got nothing to do with the depth setting here)
2. In the test_voc.py file, line 129, why the num_feature value for resnet-50 is 1024 ? It's neither 512 as in the resnet_py value nor the output resnet-50 feature map output dimension ?
Thank You :)

**Comment by FrancescoManigrass** [comment]
@TiasM  are you able to reproduce pascal voc results with Resnet50 ?
