### ISSUE TITLE
Set Up Keras-FasterRCNN in local machine from scratch

### ISSUE THREAD

**Issue by samrawitergrtr** [kentaroy47/frcnn-from-scratch-with-keras#75]
Hi.
I wanted to use Keras-FasterRCNN using Anaconda in my local machine but i couldn't do it .Please can anyone show me how to set it up step by step?
Thank You!

**Comment by kentaroy47** [comment]
Just following readme should setup the repo.
If you're stuck and need help, you should write what step and what errors you got.

**Comment by samrawitergrtr** [comment]
@kentaroy47 
I finished step 1 and 2 but in step 3 when i run train_rpn.py to train region proposal network i face with this error

ModuleNotFoundError: No module named 'tensorflow.python.platform'

**Comment by kentaroy47** [comment]
Do you have tensorflow and keras installed? Maybe that is the cause.

2020年4月9日(木) 17:50 samrawitergrtr <notifications@github.com>:

**Comment by samrawitergrtr** [comment]
@kentaroy47 
Yes did.
        Name: tensorflow
        Version: 1.15.0
.
.
.
and
        Name: Keras
        Version: 2.2.4

**Comment by samrawitergrtr** [comment]
This is what it looks like
![eror](https://user-images.githubusercontent.com/60253058/78878731-b9df4b80-7a07-11ea-816f-8ae736c60bb0.PNG)

The Installation
![frcnn](https://user-images.githubusercontent.com/60253058/78878348-1db54480-7a07-11ea-8fd5-503f8b0edef8.PNG)

**Comment by kentaroy47** [comment]
Looks like a tensorflow related error and not related to frcnn to me.
Do simple demo scripts like mnist run on your system?

2020年4月9日(木) 18:14 samrawitergrtr <notifications@github.com>:

**Comment by samrawitergrtr** [comment]
@kentaroy47 
No the same problem happened.

**Comment by kentaroy47** [comment]
You should google the error itself or ask in the tensorflow community!
Hope it helps.

**Comment by samrawitergrtr** [comment]
@kentaroy47 
Thank You!

**Comment by samrawitergrtr** [comment]
I have another question.
Can i train first feature map then RPN and ROI individually?
Because i wanted to see the training model accuracy of all.
If their is any example that you know or maybe a link can you help me?
