### ISSUE TITLE
train_rpn.py resnet50 silently closed

### ISSUE THREAD

**Issue by dsounded** [kentaroy47/frcnn-from-scratch-with-keras#76]
Not sure what happened but it just stopped on epoch n6 and step 572, no additional logs provided. Can you please help telling what this is potential might be ?
I am using custom dataset: 11k of images 256x256.

**Comment by dsounded** [comment]
yet again, it stopped on n6 ...

**Comment by kentaroy47** [comment]
Might be memory error? Stop other task or enlarge swap?

2020年4月16日(木) 14:55 Kiril Dokh <notifications@github.com>:

**Comment by dsounded** [comment]
I use Google cloud console with pretty descent setup, not sure if this can be related...

**Comment by dsounded** [comment]
@kentaroy47 actually fixed that one... but now I want to get the example during training process (checkpoint) and test it. 

Am I wright that I need to recreate full architecture using let's say training script with the given checkpoints weights ?

I did so and then saved it with `keras` `save()` using:
`loaded = load_model('name.h5', custom_objects={'RoiPoolingConv':RoiPoolingConv})`
without `RoiPoolingConv` part it threw the error.

Then I want to convert the model to `onnx`
I tried https://github.com/onnx/keras-onnx

But had no luck with...
`AttributeError: The layer has never been called and thus has no defined input shape.`

I know this is kind of offtopic, but maybe you know what's the issue and how I can fix it...
