### ISSUE TITLE
classifier_layers not used in resnet.py

### ISSUE THREAD

**Issue by YiJunLing** [kentaroy47/frcnn-from-scratch-with-keras#89]
Hi, I'm not sure if this is intentional but it would seem classifier_layer (the last block of resnet) function is not used in resnet.py. Thank you.

**Comment by kentaroy47** [comment]
Thanks for the issue!
In object detection, the classifier layer is not used and only the conv feature extractor layers are used.
I'm going to close this since it is intentional.

**Comment by YiJunLing** [comment]
Alright. Thanks for responding!
