### ISSUE TITLE
Do VOC format oblige to provide input data as a rectangle two corner points or I can provide object position as polygon?

### ISSUE THREAD

**Issue by chamecall** [kentaroy47/frcnn-from-scratch-with-keras#9]

**Comment by kentaroy47** [comment]
Its xmin, ymin, xmax, ymax.

Ken

**Comment by chamecall** [comment]
> Its xmin, ymin, xmax, ymax.
Strictly this format. I understood correctly?

**Comment by kentaroy47** [comment]
Yes, only this. Coco is this format too.

2019年7月18日(木) 20:07 chamecall <notifications@github.com>:
