### ISSUE TITLE
RPN weights are not saved

### ISSUE THREAD

**Issue by sivaramakrishnan-rajaraman** [kentaroy47/frcnn-from-scratch-with-keras#90]
I ran the train_rpn.py script and attempted to save the model under the root directory under models/rpn. This is the code according to the repository:
Callbacks=keras.callbacks.ModelCheckpoint("models/rpn/rpn."+options.network+".weights.{epoch:02d}-{val_loss:.2f}.hdf5", monitor='val_loss', verbose=1, save_best_only=False, save_weights_only=True, mode='auto', period=4)
callback=[Callbacks]
history = model_rpn.fit_generator(data_gen_train,
                    epochs=options.num_epochs, validation_data=data_gen_val,
                    steps_per_epoch=1000,callbacks=callback, validation_steps=10)

The model is training but after completion, the weights are neither getting created nor stored under the directory. My Keras version is 2.2.4.

**Comment by kentaroy47** [comment]
Thanks for the head's up.
You may need to create the `models/rpn` if it does not exist. (Should have added this with os.makedir, sry.)

**Comment by kentaroy47** [comment]
closing since no response.
